name: Test and Lint

on:
  workflow_call:
    secrets:
      DOCKERHUB_USER:
        required: true
        description: "Username for DockerHub auth"
      DOCKERHUB_TOKEN:
        required: true
        description: "Token for DockerHub auth"

jobs:
  python:
    name: Python
    runs-on: ubuntu-22.04
    steps:
      - name: Print DockerHub Credentials (for debugging — values will be masked)
        run: |
          echo "Logging in to DockerHub with:"
          echo "Username: ${{ secrets.DOCKERHUB_USER }}"
          echo "Token: ${{ secrets.DOCKERHUB_TOKEN }}"
